spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.160.249:3306/todo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: todo8
    password: 1234
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
logging:
  pattern:
    console: "%date  %highlight(%-5level) %cyan(%-40.40logger{40}) : %msg%n"
  level:
    org.springframework.web: error
    com.codesquad.todo8: debug
    sql: debug

jwt:
  token:
    secret: Il9g5guhxIzpOz+uxvHF9DBY+hv9R9a6yBEzeqvFobA=

